name: 'Release'

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Сборка
    runs-on: ubuntu-latest
    outputs:
      ARTIFACT_PATH: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_PATH }}
      ARTIFACT_NAME: ${{ steps.prepare_artifact_metadata.outputs.ARTIFACT_NAME }}
      JAVADOC_PATH: ${{ steps.prepare_artifact_metadata.outputs.JAVADOC_PATH }}
      JAVADOC_NAME: ${{ steps.prepare_artifact_metadata.outputs.JAVADOC_NAME }}
      API_PATH: ${{ steps.prepare_artifact_metadata.outputs.API_PATH }}
      API_NAME: ${{ steps.prepare_artifact_metadata.outputs.API_NAME }}
      VERSION: ${{ steps.prepare_artifact_metadata.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - run: git fetch origin --tags
        shell: bash
      - uses: ./.github/actions/gradle-setup
      - name: Сборка с помощью Gradle
        run: ./gradlew printProjectVersion build publish
        
